# ---------------------------------------------
# Anchors for Common Configurations
# ---------------------------------------------
x-drive-common:
  &drive-common
  restart: always
  networks:
    - drive-monitoring
  healthcheck:
    &uniform-frequency
    interval: 10s
    timeout: 5s
    retries: 3
  
x-drive-logging:
  &drive-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}" 
  
x-lables:
  labels:
     &drive-labels
    com.project.name: "PROJCET DRIVE"
    com.drive.description: "DRIVE application"
    com.drive.supported_os: "ubuntu, debian"
    com.drive.deployment: "docker"

# ------------------------------------------------------
# Setup Agents Monitoring Stack on other DRIVE servers 
# ------------------------------------------------------
services:
  monitoring-cadvisor:
    <<: *drive-common
    image: ${CADVISOR_IMAGE}
    container_name: monitoring-cadvisor
    hostname: monitoring-cadvisor
    privileged: true
    ports:
      - 5003:8080
    command:
      - '-housekeeping_interval=15s'
      - '-docker_only=true'
      - '-store_container_labels=false'
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/machine-id:/etc/machine-id:ro
    healthcheck: 
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/metrics"]
      <<: *uniform-frequency
    labels:
      <<: *drive-labels
    logging:
      <<: *drive-logging

  monitoring-node-exporter:
    <<: *drive-common
    image: ${NODE_EXPORTER_IMAGE}
    container_name: monitoring-node-exporter
    hostname: monitoring-node-exporter
    ports:
      - 5004:9100
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/host
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    healthcheck: 
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:9100/metrics"]
      <<: *uniform-frequency
    logging:
      <<: *drive-logging

#-----------------------------------------------------------------------------------------------
#                                      DRIVE LOGGING
#-----------------------------------------------------------------------------------------------
  logging-promtail:
    <<: *drive-common
    image: ${PROMTAIL_IMAGE}
    container_name: logging-promtail
    volumes:
    - /var/log:/var/log:ro
    - /var/lib/docker/containers:/host/containers:ro
    - ./logging/promtail/agents-server:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      logging-loki:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "ls", "/var/log"]
      <<: *uniform-frequency
    labels:
      <<: *drive-labels
    logging:
      <<: *drive-logging

volumes:
  grafana_data:
    name: grafana_data
  prometheus_data:
    name: prometheus_data
  
networks:
  drive-monitoring:
    name: drive-monitoring
    driver: bridge