# DRIVE global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
#rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']    # Prometheus on STG01

  - job_name: 'control-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['monitoring-cadvisor:8080']        # cAdvisor on STG01

  - job_name: 'control-node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['monitoring-node-exporter:9100']   # Node Exporter on STG01
  
  - job_name: 'agents-cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'STG02_IP:5003'   # cAdvisor on STG02
          - 'DEV01_IP:5003'   # cAdvisor on DEV01
          - 'DEV02_IP:5003'   # cAdvisor on DEV02
          - 'DEV03_IP:5003'   # cAdvisor on DEV03

  - job_name: 'agents-node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'STG02_IP:5004'   # Node Exporter on STG02
          - 'DEV01_IP:5004'   # Node Exporter on DEV01
          - 'DEV02_IP:5004'   # Node Exporter on DEV02
          - 'DEV03_IP:5004'   # Node Exporter on DEV03
